development:
  adapter: mysql2
  encoding: utf8
  database: geocode_service
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: geocode_service
  username: root
  password:
  socket: /tmp/mysql.sock
